Fix check build frontend.yml

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -38,5 +38,5 @@ jobs:
       # Étape 5 : Vérifier que le build a réussi
       - name: Verify Build Success
         run: |
-          if [ ! -d "out" ]; then echo "Build failed"; exit 1; fi
+          if [ ! -d "frontend/.next" ]; then echo "Build failed"; exit 1; fi
         working-directory: ./frontend 
